spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://10.0.10.25:3306/locals_production
    username: javadb
    password: db@locals2017!
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: info