spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://x:3306/seata
    username: x
    password: x
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: info