spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://x:3306/seata?useInformationSchema=false&allowMultiQueries=true
    username: x
    password: x
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        applicationId: business-service
        tx-service-group: my_test_tx_group
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: info
server:
  port: 8084